# This is a basic workflow to help you get started with Actions

name: Scrape Google Scholar

on:
  schedule:
    - cron: "*/5 * * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        R: ['3.5.3']
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - name: Install dependencies
        run: |
          install.packages("xml2")
          install.packages("rvest")
          install.packages("httr")
          install.packages("stringr")
          install.packages("dplyr")
        shell: Rscript {0}
      - run: Rscript get_citations.R
